### PR TITLE
proposed feature: support for Yaml symbol keys

### PR DESCRIPTION
**Pull request by ultrasaurus**
I recently tried to switch from using ActiveHash to ActiveYaml
ActiveHash supports both symbol and string keys
this change allows for indifferent_access option 
this PR is on top of pr_90 branch where tests pass

### CODE REVIEW

**Comment by zilkey** [comment]
Fancy :)

Any reason to not use ActiveSupport's HashWithIndifferentAccess?  http://api.rubyonrails.org/v4.2/classes/ActiveSupport/HashWithIndifferentAccess.html

**Comment by ultrasaurus** [comment]
@zilkey wow.  This was a while ago!  Sorry if I'm missing something obvious... how would HashWithIndifferentAccess solve this?  do you mean somehow use that instead of ActiveYAML?  or somewhere in the implementation?

**Comment by syguer** [comment]
@ultrasaurus while ago again.
It means you should use `HashWithIndifferentAccess` instead of your implementation(`#deep_symbolize_keys`)

Is you still interested in this?

**Comment by syguer** [comment]
I'll close this. If you need this again, please reopen.
Thanks.

**Pull request closed without merging**
