### PR TITLE
WIP Warning

### PR DESCRIPTION
**Pull request by tamgrosser**
@grosser

### CODE REVIEW

**Comment by grosser** [comment]
somehow has_insance_method? returned false after define_method was called
leading to duplicate method definitions and warnings

instead of fixing this mystery bug I'm just removing the obsolete method

@kbrock

**Comment by kbrock** [comment]
@grosser Great fixes.

I'm not comfortable with the 1.8.7. I got pushback trying to drop it in another gem. (If my name were in the url I'd feel like I had more jurisdiction to make this change)

Dropping ruby would force this to 2.0, or would 1.5 work too?

If you pull out the 1.8.7, then I'll merge right away.

Alternatively, @zilkey - you ok dropping 1.8.7? I'm mixed. (if you say go, then lets merge)

**Comment by grosser** [comment]
whoever is stuck on 1.8 can always use an old version of this project ... 
in 2015 that was 1% ... so let's not optimize for the `< 1%` ... 
https://semaphoreci.com/blog/2015/12/01/ruby-version-usage-in-commercial-projects-2015-edition.html

**Comment by grosser** [comment]
🎉

**Pull request merged**
