### PR TITLE
Fix a bug that returns nil instead of empty array from 575fe9d

### PR DESCRIPTION
**Pull request by syguer**
I'm sorry, I released v1.5.0 several days ago, but It has breaking bug.
I fixed that issue.

### CODE REVIEW

**Comment by syguer** [comment]
@kbrock 
After your review, I'm going to add bump up commit and documentation :)

**Comment by syguer** [comment]
@zilkey @kbrock no opinion? I'll push this fix soon because this is breaking change...

**Comment by kbrock** [comment]
@syguer sorry - looks good.
Thanks for giving heads up, and thanks for not waiting too long on either of us, too.

**Comment by syguer** [comment]
No problem, thank you for review!

**Pull request merged**
