### PR TITLE
Implement .find_by!

### PR DESCRIPTION
**Pull request by syguer**
After merged,  API is added.
So I think it should bump up minor version 😄

### CODE REVIEW

**Comment by syguer** [comment]
I'll continuously maintain this awesome gem.
Can you add me to collaborators, and Gem owners? @zilkey

**Comment by syguer** [comment]
hello? @zilkey

**Comment by zilkey** [comment]
Awesome!  (sorry for the delay - just back from a quick vacation).  I'll add you now.

**Comment by syguer** [comment]
Oh, sorry. And thank you for your invitation! 🎉

**Pull request merged**
